[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "0xff0000"
text = "0x000000"

[colors.dim]
black = "0x000000"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x505000"
magenta = "0xcc99cc"
red = "0x400000"
white = "0xdddddd"
yellow = "0x805000"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xa0a000"
magenta = "0xc397d8"
red = "0xd03000"
white = "0xffffff"
yellow = "0xe0a000"

[colors.primary]
background = "0x000000"
foreground = "0xd03000"

[font]
size = 12.0

[terminal]
shell = { args = ["-c", "test -x /run/current-system/sw/bin/tmux && exec /run/current-system/sw/bin/tmux new -As0 || test -x /bin/tmux && exec /bin/tmux new -As0 || test -x /bin/zsh && exec /bin/zsh || test -x /bin/bash && exec /bin/bash || exec /bin/sh", ], program = "/bin/sh" }
